### ISSUE TITLE
feel free to make a PR in my extension if you think any of your snippets are general-purpose enough

### ISSUE THREAD

**Issue by jedwards1211** [ouweiya/mui-snippets#2]

**Comment by ouweiya** [comment]
At first I hoped to do the same, but I saw that you use TypeScript, I am not good at this, I just use snippets for quick use, so the code is not good enough, and I am afraid of causing bad damage.

**Comment by jedwards1211** [comment]
Oh I see.  Adding/copying and modifying a snippet file to this project doesn't really require any typescript knowledge anyway, so there's not much risk of causing damage.  Even if there were an issue with a PR I could give tips or help fix it.  No worries either way, just wanted to extend an invitation.

**Comment by ouweiya** [comment]
Okay, you dispelled my worries, I think I will do it.
